version: "3.9"

services:
    bot:
        build: .
        ports: 
            - "5000:5000"
        volumes:
            - type: bind
              source: ./database.db
              target: /database.db

volumes:
    bot-data: